package org.jbpm.process.migration;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcessData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Position(value = 0)
	private java.lang.String deploymentId;
	@org.kie.api.definition.type.Position(value = 1)
	private java.lang.Long processInstanceId;
	@org.kie.api.definition.type.Position(value = 2)
	private java.lang.String toProcessId;
	@org.kie.api.definition.type.Position(value = 3)
	private java.lang.String toDeploymentId;

	public java.lang.String getDeploymentId() {
		return this.deploymentId;
	}

	public void setDeploymentId(java.lang.String deploymentId) {
		this.deploymentId = deploymentId;
	}

	public java.lang.Long getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.Long processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public java.lang.String getToProcessId() {
		return this.toProcessId;
	}

	public void setToProcessId(java.lang.String toProcessId) {
		this.toProcessId = toProcessId;
	}

	public java.lang.String getToDeploymentId() {
		return this.toDeploymentId;
	}

	public void setToDeploymentId(java.lang.String toDeploymentId) {
		this.toDeploymentId = toDeploymentId;
	}

	public ProcessData() {
	}

	public ProcessData(java.lang.String deploymentId,
			java.lang.Long processInstanceId, java.lang.String toProcessId,
			java.lang.String toDeploymentId) {
		this.deploymentId = deploymentId;
		this.processInstanceId = processInstanceId;
		this.toProcessId = toProcessId;
		this.toDeploymentId = toDeploymentId;
	}

	@Override
	public String toString() {
		return "ProcessData [deploymentId=" + deploymentId
				+ ", processInstanceId=" + processInstanceId + ", toProcessId="
				+ toProcessId + ", toDeploymentId=" + toDeploymentId + "]";
	}

}