package org.jbpm.sample.assistant;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Question implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String question;
	private java.lang.Boolean answered;
	private java.lang.String answer;

	public Question() {
	}

	public java.lang.String getQuestion() {
		return this.question;
	}

	public void setQuestion(java.lang.String question) {
		this.question = question;
	}

	public java.lang.Boolean getAnswered() {
		return this.answered;
	}

	public void setAnswered(java.lang.Boolean answered) {
		this.answered = answered;
	}

	public java.lang.String getAnswer() {
		return this.answer;
	}

	public void setAnswer(java.lang.String answer) {
		this.answer = answer;
	}

	public Question(java.lang.String question, java.lang.Boolean answered,
			java.lang.String answer) {
		this.question = question;
		this.answered = answered;
		this.answer = answer;
	}
	
	public String toString() {
	    return "Question[" + question + ", " + answer + "]";
	}

}