package com.redhat.jboss.hr.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(5e5c6d481ae785288af1e0f55b8963a1)
 */
@org.kie.api.definition.type.Label(value = "Award")
public class Award extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "Award amount")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer amount;
    
    @org.kie.api.definition.type.Label(value = "Explaination")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String explaination;

    public Award() {
    }

    public Award(java.lang.Integer amount, java.lang.String explaination) {
        this.amount = amount;
        this.explaination = explaination;
    }


    
    public java.lang.Integer getAmount() {
        return this.amount;
    }

    public void setAmount(java.lang.Integer amount) {
        this.amount = amount;
    }
    
    public java.lang.String getExplaination() {
        return this.explaination;
    }

    public void setExplaination(java.lang.String explaination) {
        this.explaination = explaination;
    }
}